---
title: "Turtle_Loops"
author: "Harman Singh"
date: "2023-04-24"
output: html_document
---

# Install packages and load libraries

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install package
#install.packages("TurtleGraphics")

# load library
library(TurtleGraphics)
library(foreach)
library(doParallel)

```

# Turtle Forest

```{r}
# start_time <- Sys.time()
# 
# fractal_tree<-function(s=100,n=2){
#   if(n<=1){
#     turtle_forward(s)
#     turtle_up()
#     turtle_backward(s)
#     turtle_down()
#     }
#   else{
#     turtle_forward(s)
#     a1<-runif(1,10,60)
#     turtle_left(a1)
#     fractal_tree(s*runif(1,0.25,1),n-1)
#     turtle_right(a1)
# 
#     a2<-runif(1,10,60)
#     turtle_right(a2)
#     fractal_tree(s*runif(1,0.25,1),n-1)
#     turtle_left(a2)
#     turtle_up()
#     turtle_backward(s)
#     turtle_down()
#     }
#   }
# set.seed(123)
# turtle_init(500,600,"clip")
# turtle_do({ turtle_up()
#   turtle_backward(250)
#   turtle_down()
#   turtle_col("darkgreen")
#   fractal_tree(100,12)
#   })
# 
# 
# 
# # Define a function to draw a forest of fractal trees
# drawForest <- function(numTrees, maxDepth, maxLength) {
#   # Set the turtle graphics window size
#   turtle_init(width = 1200, height = 1200)
#   
#   # Loop through each tree
#   for (i in 1:numTrees) {
#     # Set the turtle graphics position and angle
#     turtle_up()
#     turtle_forward(runif(1, -500, 500))
#     turtle_right(runif(1, 0, 360))
#     
#     # Draw the tree
#     fractal_tree(depth = round(runif(1, 1, maxDepth)), length = runif(1, 50, maxLength))
#   }
#   
#   # Save the image
#   dev.copy(png, "turtle_plot.png", width = 800, height = 800)
#   dev.off()
# }
# 
# # Draw a forest of fractal trees with 10 trees, maximum depth of 6, and maximum length of 200
# drawForest(numTrees = 10, maxDepth = 6, maxLength = 200)
# 
# end_time <- Sys.time()
# 
# end_time - start_time

```

```{r}
start_time <- Sys.time()

drawTree <- function(depth, length, angle1 = 30, angle2 = 25, factor = 0.7) {
  if (depth == 0) {
    turtle_forward(length)
    turtle_backward(length)
  } else {
    turtle_forward(length)
    turtle_right(angle1)
    drawTree(depth - 1, length * factor, angle1, angle2, factor)
    turtle_left(angle1 + angle2)
    drawTree(depth - 1, length * factor, angle1, angle2, factor)
    turtle_right(angle2)
    drawTree(depth - 1, length * factor, angle1, angle2, factor)
    turtle_left(angle2 + angle1)
    drawTree(depth - 1, length * factor, angle1, angle2, factor)
    turtle_right(angle1)
    turtle_backward(length)
    turtle_col("darkgreen")
  }
}

# Define a function to draw a forest of fractal trees
drawForest <- function(numTrees, maxDepth, maxLength) {
  # Set the turtle graphics window size
  turtle_init(width = 1200, height = 1200, mode = 'cycle')
  
  # Loop through each tree
  for (i in 1:numTrees) {
    # Set the turtle graphics position and angle
    turtle_up()
    turtle_forward(runif(1, -500, 500))
    turtle_right(runif(1, 0, 360))
    
    # Draw the tree
    drawTree(depth = round(runif(1, 1, maxDepth)), length = runif(1, 50, maxLength))
  }
  
  # Save the image
  dev.copy(png, "turtle_plot.png", width = 800, height = 800)
  dev.off()
}

# Draw a forest of fractal trees with 10 trees, maximum depth of 6, and maximum length of 200
drawForest(numTrees = 10, maxDepth = 6, maxLength = 200)

end_time <- Sys.time()

end_time - start_time

```

